name: Deploy NH Staging Website to Server via FTP

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./
          server-dir: nhhomestaging.ca/
          log-level: verbose
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            images/README.md
            design-system/**
            README.md
            node_modules/**